name: Ed Coyne
markdown: kramdown
defaults:
    -
      scope:
          path: "_posts/"
      values:
          layout: "post"
collections:
    - topics
        output: true
        permalink: /topics/:path/
